# Generated by Django 3.2.7 on 2021-12-08 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliver',
            fields=[
                ('deliver_id', models.AutoField(primary_key=True, serialize=False)),
                ('typedni', models.CharField(max_length=25)),
                ('dni', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=15)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('delivery_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=40)),
                ('details', models.TextField()),
                ('deliver_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userfarmapp.deliver')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('typedni', models.CharField(max_length=25, verbose_name='Typedni')),
                ('dni', models.CharField(max_length=15, verbose_name='Dni')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('lastname', models.CharField(max_length=30, verbose_name='Lastname')),
                ('eps', models.CharField(max_length=40, verbose_name='Eps')),
                ('gender', models.CharField(max_length=20, verbose_name='Gender')),
                ('address', models.CharField(max_length=50, verbose_name='Address')),
                ('telephone', models.CharField(max_length=15, verbose_name='Telephone')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
